# Generated by Django 3.0.8 on 2020-07-23 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0002_onetimepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='created_at',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onetimepassword', to=settings.AUTH_USER_MODEL),
        ),
    ]
