# Generated by Django 3.0.8 on 2020-07-23 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0003_auto_20200723_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='balancesheet')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('Assam', 'Assam'), ('Delhi', 'Delhi')], default='Assam', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('company_type', models.CharField(choices=[('LTD', 'LTD'), ('LLC', 'LLC')], default='LTD', max_length=200)),
                ('sub_type', models.CharField(choices=[('LTD', 'LTD'), ('LLC', 'LLC')], default='LTD', max_length=200)),
                ('industry', models.CharField(choices=[('TEXTILE', 'TEXTILE'), ('STEEL', 'STEEL')], default='TEXTILE', max_length=200)),
                ('sale_description', models.CharField(blank=True, max_length=500)),
                ('year_of_incorporation', models.IntegerField(blank=True, null=True)),
                ('has_gst_number', models.BooleanField(null=True)),
                ('has_import_export_code', models.BooleanField(null=True)),
                ('has_bank_account', models.BooleanField(null=True)),
                ('has_other_license', models.BooleanField(null=True)),
                ('other_license', models.CharField(blank=True, max_length=500)),
                ('capital', models.IntegerField(blank=True, null=True)),
                ('user_defined_selling_price', models.IntegerField(blank=True, null=True)),
                ('admin_defined_selling_price', models.IntegerField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_text', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalancesheetPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
                ('balancesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancesheetpayments', to='corpmart.Balancesheet')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancesheetpayments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancesheets', to='corpmart.Business'),
        ),
    ]
