# Generated by Django 3.0.8 on 2020-07-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0004_auto_20200723_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('picture', models.ImageField(blank=True, upload_to='profile_picture')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.IntegerField(default=91),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
