# Generated by Django 3.0.8 on 2020-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0005_auto_20200724_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
