# Generated by Django 3.0.8 on 2020-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0006_user_organisation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
