# Generated by Django 3.0.8 on 2020-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0007_business_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(null=True),
        ),
    ]
