# Generated by Django 3.0.8 on 2020-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0008_auto_20200724_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_by',
            field=models.CharField(max_length=100),
        ),
    ]
