# Generated by Django 3.0.8 on 2020-07-24 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0009_auto_20200724_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='corpmart.Business')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactrequests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('requested_by', 'business')},
            },
        ),
    ]
