# Generated by Django 3.0.8 on 2020-07-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0011_contactrequest_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheetpayment',
            old_name='paid_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='balancesheetpayment',
            old_name='paid_on',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='balancesheetpayment',
            old_name='paid_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='balancesheetpayment',
            name='id',
        ),
        migrations.AddField(
            model_name='balancesheetpayment',
            name='order_id',
            field=models.CharField(default='default', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancesheetpayment',
            name='payment_sucessful',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheetpayment',
            name='razorpay_order_id',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancesheetpayment',
            name='razorpay_payment_id',
            field=models.CharField(default='default', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancesheetpayment',
            name='razorpay_signature',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balancesheets', to='corpmart.Business'),
        ),
        migrations.AlterField(
            model_name='balancesheetpayment',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
