# Generated by Django 3.0.8 on 2020-07-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0012_auto_20200725_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheetpayment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='balancesheetpayment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='balancesheetpayment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
