# Generated by Django 3.0.8 on 2020-07-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0013_auto_20200725_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheetpayment',
            old_name='payment_sucessful',
            new_name='payment_successful',
        ),
    ]
