# Generated by Django 3.0.8 on 2020-07-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0014_auto_20200726_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(unique=True),
        ),
    ]
