# Generated by Django 3.0.8 on 2020-07-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0015_auto_20200726_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='company_type_others_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='industries_others_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='sub_type_others_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='company_type',
            field=models.CharField(blank=True, choices=[('Pvt Ltd', 'Pvt Ltd'), ('Limited Liability Partnership (LLP)', 'Limited Liability Partnership (LLP)'), ('Partnership Firm', 'Partnership Firm'), ('Trust/Society', 'Trust/Society'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(blank=True, choices=[('AGRICULTURE AND ALLIED INDUSTRIES', 'AGRICULTURE AND ALLIED INDUSTRIES'), ('AUTOMOBILES', 'AUTOMOBILES'), ('AUTO COMPONENTS', 'AUTO COMPONENTS'), ('AVIATION', 'AVIATION'), ('BANKING', 'BANKING'), ('CEMENT', 'CEMENT'), ('CONSUMER DURABLES', 'CONSUMER DURABLES'), ('ECOMMERCE', 'ECOMMERCE'), ('EDUCATION AND TRAINING', 'EDUCATION AND TRAINING'), ('ENGINEERING AND CAPITAL GOODS', 'ENGINEERING AND CAPITAL GOODS'), ('FINANCIAL SERVICES', 'FINANCIAL SERVICES'), ('FMCG', 'FMCG'), ('GEMS AND JEWELLERY', 'GEMS AND JEWELLERY'), ('HEALTHCARE', 'HEALTHCARE'), ('INFRASTRUCTURE', 'INFRASTRUCTURE'), ('INSURANCE', 'INSURANCE'), ('IT & ITES', 'IT & ITES'), ('MANUFACTURING', 'MANUFACTURING'), ('MEDIA AND ENTERTAINMENT', 'MEDIA AND ENTERTAINMENT'), ('METALS AND MINING', 'METALS AND MINING'), ('OIL AND GAS', 'OIL AND GAS'), ('PHARMACEUTICALS', 'PHARMACEUTICALS'), ('PORTS', 'PORTS'), ('POWER', 'POWER'), ('RAILWAYS', 'RAILWAYS'), ('REAL ESTATE', 'REAL ESTATE'), ('RENEWABLE ENERGY', 'RENEWABLE ENERGY'), ('RETAIL', 'RETAIL'), ('ROADS', 'ROADS'), ('SCIENCE AND TECHNOLOGY', 'SCIENCE AND TECHNOLOGY'), ('SERVICES', 'SERVICES'), ('STEEL', 'STEEL'), ('TELECOMMUNICATIONS', 'TELECOMMUNICATIONS'), ('TEXTILES', 'TEXTILES'), ('TOURISM AND HOSPITALITY', 'TOURISM AND HOSPITALITY'), ('OTHERS', 'OTHERS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Puducherry', 'Puducherry'), ('Ladakh', 'Ladakh')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('One Person Company', 'One Person Company'), ('Producer Company', 'Producer Company'), ('Nidhi Company', 'Nidhi Company'), ('Section-8 Company(NGO)', 'Section-8 Company(NGO)'), ('Non-Banking Financial Company (NBFC)', 'Non-Banking Financial Company (NBFC)'), ('Micro-Finance Company', 'Micro-Finance Company'), ('Insurance Company', 'Insurance Company'), ('Direct Selling Company', 'Direct Selling Company'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
