# Generated by Django 3.0.8 on 2020-07-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0016_auto_20200727_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(),
        ),
    ]
