# Generated by Django 3.0.8 on 2020-07-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0019_auto_20200727_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
    ]
