# Generated by Django 3.0.8 on 2020-07-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0021_auto_20200729_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='verified_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='processed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='processed_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='BalancesheetPayment',
        ),
    ]
