# Generated by Django 3.0.8 on 2020-07-29 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0022_auto_20200729_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewhistory', to='corpmart.Business')),
                ('viewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewhistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
