# Generated by Django 3.0.8 on 2020-07-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0023_viewhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'verbose_name_plural': 'ViewHistory'},
        ),
        migrations.RenameField(
            model_name='business',
            old_name='capital',
            new_name='authorised_capital',
        ),
        migrations.AddField(
            model_name='business',
            name='paidup_capital',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
