# Generated by Django 3.0.8 on 2020-08-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0025_auto_20200801_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('query', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField()),
                ('processed_by', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
