# Generated by Django 3.0.8 on 2020-08-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0026_chatbotrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotrequest',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
