# Generated by Django 3.0.8 on 2020-08-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0027_auto_20200806_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='company_type',
            field=models.CharField(blank=True, choices=[('Pvt. Ltd.', 'Pvt. Ltd.'), ('Limited Liability Partnership (LLP)', 'Limited Liability Partnership (LLP)'), ('Partnership Firm', 'Partnership Firm'), ('Trust/Society', 'Trust/Society'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
