# Generated by Django 3.0.8 on 2020-08-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0028_auto_20200809_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
