# Generated by Django 3.0.8 on 2020-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0030_auto_20200813_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, upload_to='blog_picture'),
        ),
    ]
