# Generated by Django 3.0.8 on 2020-08-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0031_blog_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
