# Generated by Django 3.0.8 on 2020-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0032_auto_20200815_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotrequest',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
