# Generated by Django 3.0.8 on 2020-08-30 11:24

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0034_auto_20200822_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
