# Generated by Django 3.0.8 on 2020-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0035_auto_20200830_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry'), ('Ladakh', 'Ladakh')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('One Person Company', 'One Person Company'), ('Producer Company', 'Producer Company'), ('Nidhi Company', 'Nidhi Company'), ('Section-8 Company(NGO)', 'Section-8 Company(NGO)'), ('Non-Banking Financial Company (NBFC)', 'Non-Banking Financial Company (NBFC)'), ('Micro-Finance Company', 'Micro-Finance Company'), ('Insurance Company', 'Insurance Company'), ('Direct Selling Company', 'Direct Selling Company'), ('Pvt. Ltd.', 'Pvt. Ltd.'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
