# Generated by Django 3.0.8 on 2020-09-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpmart', '0036_auto_20200923_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='has_import_export_code',
            new_name='roc_up_to_date',
        ),
    ]
